#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# nushell-config-bootstrap.sh
#
# Generate a reproducible Nushell config repo (Nu 0.109+), using here-docs,
# and optionally install thin wrappers into ~/.config/nushell.
#
# This script:
#   - writes a clean, modular config tree into a repo directory
#   - keeps only two Nushell entry points: env.nu + config.nu
#   - loads everything else explicitly through init.nu
#   - provides local overrides via local/{env.local.nu,init.local.nu}
#   - avoids legacy Nu syntax (no let-env; no deprecated str flags)
#
# Usage:
#   ./nushell-config-bootstrap.sh [--repo-dir PATH] [--install] [--force]
#
# Notes:
#   - You are expected to commit the generated repo to GitHub.
#   - Local overrides are created and ignored by default (safe for per-machine).
# -----------------------------------------------------------------------------

set -euo pipefail

function die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

function help_text() {
  cat <<'EOF'
nushell-config-bootstrap.sh

Generate a reproducible Nushell config repo (Nu 0.109+), and optionally install
thin wrapper files into ~/.config/nushell.

USAGE
  nushell-config-bootstrap.sh [OPTIONS]

OPTIONS
  --repo-dir PATH
      Target directory to write the repo files into.
      Default: current working directory.

  --install
      Also write ~/.config/nushell/{env.nu,config.nu} wrappers that source the
      repo entry points.

  --force
      Overwrite existing files.

  -h, --help
      Show this help.

WHAT YOU GET
  Repo entry points:
    env.nu     (environment variables + optional integration cache gen)
    config.nu  (shell config + sources init.nu)

  Orchestrator:
    init.nu    (explicitly loads modules and scripts; nothing is implicit)

  Modules:
    modules/stdlib.nu
    modules/lib.nu

  Scripts:
    prompt.nu
    alias.nu

  Local overrides (per-machine; ignored by default):
    local/env.local.nu
    local/init.local.nu
    local/*.example.nu (tracked templates)

INSTALLATION MODEL
  Nushell only auto-loads:
    ~/.config/nushell/env.nu
    ~/.config/nushell/config.nu

  Those wrappers will source the repo env.nu/config.nu. Everything else is loaded
  explicitly from init.nu.

EOF
}

function run_help_pager() {
  local pager="${HELP_PAGER:-}"
  if [[ -z "$pager" ]]; then
    if command -v less >/dev/null 2>&1; then
      pager='less -R'
    else
      pager='cat'
    fi
  fi
  help_text | eval "$pager"
}

repo_dir="$(pwd -P)"
do_install="0"
force="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo-dir)
      [[ $# -ge 2 ]] || die "--repo-dir requires a PATH argument"
      repo_dir="$2"
      shift 2
      ;;
    --install)
      do_install="1"
      shift
      ;;
    --force)
      force="1"
      shift
      ;;
    -h|--help)
      run_help_pager
      exit 0
      ;;
    *)
      die "Unknown argument: $1 (use --help)"
      ;;
  esac
done

repo_dir="$(mkdir -p "$repo_dir" && cd "$repo_dir" && pwd -P)"

function write_file() {
  local path="$1"
  local mode="${2:-0644}"

  if [[ -e "$path" && "$force" != "1" ]]; then
    die "Refusing to overwrite existing file: $path (use --force)"
  fi

  mkdir -p "$(dirname "$path")"
  local tmp
  tmp="$(mktemp)"
  cat >"$tmp"
  install -m "$mode" "$tmp" "$path"
  rm -f "$tmp"
}

function stamp() {
  date '+%Y%m%d-%H%M%S'
}

function backup_if_exists() {
  local path="$1"
  if [[ -e "$path" ]]; then
    mv -f "$path" "${path}.bak.$(stamp)"
  fi
}

# -----------------------------------------------------------------------------
# Repo metadata
# -----------------------------------------------------------------------------
write_file "$repo_dir/README.md" 0644 <<'EOF'
# Nushell Config (Nu 0.109+)

This repo is structured to be **reproducible** and **explicit**:

- Nushell only auto-loads two files:
  - `env.nu`
  - `config.nu`

- Everything else is loaded explicitly by `init.nu`.
- Per-machine customization lives in `local/` and is ignored by default.

## Install

```bash
./scripts/install.sh
```

# What loads what

* env.nu sets environment variables and generates optional integration caches.
* config.nu configures $env.config and then sources init.nu.
* init.nu uses modules and sources prompt/aliases/local overrides.
EOF

write_file "$repo_dir/.gitignore" 0644 <<'EOF'

# Per-machine overrides (keep templates tracked; keep actual local files untracked)

local/env.local.nu
local/init.local.nu

# Cache files (generated by Nu integrations)

.cache/
EOF

-----------------------------------------------------------------------------
scripts/install.sh
-----------------------------------------------------------------------------
write_file "$repo_dir/scripts/install.sh" 0755 <<'EOF'
#!/usr/bin/env bash
-----------------------------------------------------------------------------
Install thin wrappers into ~/.config/nushell that source this repo.
-----------------------------------------------------------------------------
set -euo pipefail

function die() {
printf 'Error: %s\n' "$*" >&2
exit 1
}

function stamp() { date '+%Y%m%d-%H%M%S'; }

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
nu_dir="${XDG_CONFIG_HOME:-$HOME/.config}/nushell"

mkdir -p "$nu_dir"

for f in env.nu config.nu; do
if [[ -e "$nu_dir/$f" ]]; then
mv -f "$nu_dir/$f" "$nu_dir/$f.bak.$(stamp)"
fi
done

cat >"$nu_dir/env.nu" <<EOF

# Wrapper installed by scripts/install.sh

source-env "$repo_root"/env.nu
EOF

cat >"$nu_dir/config.nu" <<EOF

# Wrapper installed by scripts/install.sh

source $repo_root/config.nu
EOF

printf 'Installed wrappers:\n %s\n %s\n'
"$nu_dir/env.nu" "$nu_dir/config.nu"

printf '\nRepo entry points:\n %s\n %s\n'
"$repo_root/env.nu" "$repo_root/config.nu"

EOF

-----------------------------------------------------------------------------
# local overrides (templates + ignored real files)
-----------------------------------------------------------------------------

write_file "$repo_dir/local/env.local.example.nu" 0644 <<'EOF'

# local/env.local.nu (example)
# This file is sourced with source-env from env.nu if it exists.
# Put per-machine environment variables here.
# Example:
# $env.PATH ++= [($env.HOME | path join "bin")]
EOF

write_file "$repo_dir/local/init.local.example.nu" 0644 <<'EOF'

# local/init.local.nu (example)
# This file is sourced from init.nu if it exists.
# Put per-machine behavioral overrides here (aliases, hooks, keybindings).
# Example:
# $env.config = ($env.config | upsert edit_mode "vi")

EOF

# Create actual local files if missing (they are gitignored by default).
# if [[ ! -e "$repo_dir/local/env.local.nu" ]]; then
write_file "$repo_dir/local/env.local.nu" 0644 <<'EOF'

# local/env.local.nu
# Per-machine environment customizations (ignored by default).

EOF
fi

if [[ ! -e "$repo_dir/local/init.local.nu" ]]; then
write_file "$repo_dir/local/init.local.nu" 0644 <<'EOF'

# local/init.local.nu
# Per-machine behavioral customizations (ignored by default).

EOF
fi

# -----------------------------------------------------------------------------
# repo/env.nu (environment only)
# -----------------------------------------------------------------------------

write_file "$repo_dir/env.nu" 0644 <<'EOF'

# -----------------------------------------------------------------------------
# env.nu (Nu 0.109+)
# Loaded before config.nu. Keep this file about environment variables only.
# -----------------------------------------------------------------------------
def cmd-exists [name: string] -> bool {
not (which $name | is-empty)
}

# Ensure cache dir exists (Nu provides $nu.cache-dir).
mkdir $nu.cache-dir | ignore

# EDITOR / VISUAL: prefer Neovim

if (cmd-exists nvim) {
$env.EDITOR = "nvim"
$env.VISUAL = "nvim"
} else if (cmd-exists vim) {
$env.EDITOR = "vim"
$env.VISUAL = "vim"
} else {
$env.EDITOR = "vi"
$env.VISUAL = "vi"
}

# Pager defaults (external tools)

$env.PAGER = "less -R"
$env.HELP_PAGER = ($env.HELP_PAGER? | default "less -R")

# PATH additions (Nu treats PATH as list)

$env.PATH ++= [
($env.HOME | path join ".local" "bin")
"/usr/local/bin"
]

# Optional: Carapace integration cache
# We generate a cache file and later source it 
# from config.nu if present.

if (cmd-exists carapace) {
let carapace_cache = ($nu.cache-dir | path join "carapace.nu")
carapace _carapace nushell | save --force $carapace_cache
}

# Optional: Zoxide integration cache

if (cmd-exists zoxide) {
let zoxide_cache = ($nu.cache-dir | path join "zoxide.nu")
zoxide init nushell | save --force $zoxide_cache
}

# Optional: Starship env marker (prompt wiring is in prompt.nu)

if (cmd-exists starship) {
$env.STARSHIP_SHELL = "nu"
}

# Local per-machine overrides (kept out of git by default)

let local_env = ($env.FILE_PWD | path join "local" "env.local.nu")
if ($local_env | path exists) {
source-env $local_env
}

EOF

# -----------------------------------------------------------------------------
# repo/config.nu (shell config + source init.nu)
# -----------------------------------------------------------------------------

write_file "$repo_dir/config.nu" 0644 <<'EOF'

# -----------------------------------------------------------------------------
# config.nu (Nu 0.109+)
# Configure $env.config and then source init.nu (explicit wiring).
# -----------------------------------------------------------------------------
def cmd-exists [name: string] -> bool {
not (which $name | is-empty)
}

# External completers (Fish + Carapace), with safe fallbacks.

let fish_completer = {|spans: list<string>|
if not (cmd-exists fish) { return null }
fish --command $'complete "--do-complete=($spans | str join " ")"'
| from tsv --flexible --noheaders --no-infer
| rename value description
}

let carapace_completer = {|spans: list<string>|
if not (cmd-exists carapace) { return null }
carapace $spans.0 nushell ...$spans | from json
}

# Work around alias completion edge-cases by expanding aliases first.
let external_completer = {|spans: list<string>|
let expanded_alias = (
scope aliases
| where name == $spans.0
| get -o 0.expansion
)

let spans = if $expanded_alias != null {
$spans | skip 1 | prepend ($expanded_alias | split row ' ' | take 1)
} else {
$spans
}

match $spans.0 {
git => $fish_completer
nu => $fish_completer
_ => $carapace_completer
} | do $in $spans
}

# Core config tweaks layered on defaults 
# (avoid overwriting the entire record).

$env.config = ($env.config | upsert show_banner false)
$env.config = ($env.config | upsert edit_mode "vi")
$env.config = ($env.config | upsert buffer_editor ($env.EDITOR | default "nvim"))

# History: durable + large

$env.config = ($env.config | upsert history {
max_size: 200_000
sync_on_enter: true
file_format: "sqlite"
isolation: true
})

# Better completions

$env.config = ($env.config | upsert completions {
case_sensitive: false
quick: true
partial: true
algorithm: "fuzzy"
external: {
enable: true
completer: $external_completer
}
})

# Display output: deep table only on wide terminals.

let hooks2 = (
$env.config.hooks
| merge {
command_not_found: {|cmd_name|
if not (cmd-exists pkgfile) { return null }
try {
let pkgs = (pkgfile --binaries --verbose $cmd_name)
if ($pkgs | is-empty) { return null }
$"($cmd_name) may be found in:\n($pkgs)"
} catch { null }
}
}
)
$env.config = ($env.config | upsert hooks $hooks2)

# Optional: source cached integrations generated in env.nu.

let carapace_cache = ($nu.cache-dir | path join "carapace.nu")
if ($carapace_cache | path exists) {
source $carapace_cache
}

let zoxide_cache = ($nu.cache-dir | path join "zoxide.nu")
if ($zoxide_cache | path exists) {
source $zoxide_cache
}

# Optional: atuin (guarded)

let atuin_init = ($env.HOME | path join ".local" "share" "atuin" "init.nu")
if ($atuin_init | path exists) {
source $atuin_init
}

# Explicit orchestration: 
# load init.nu (and everything else from there).

let init = ($env.FILE_PWD | path join "init.nu")
source $init

EOF

# -----------------------------------------------------------------------------
# repo/init.nu (orchestrator: this is where files "play together")
# -----------------------------------------------------------------------------
write_file "$repo_dir/init.nu" 0644 <<'EOF'
# -----------------------------------------------------------------------------
# init.nu (Nu 0.109+)
# Load modules + scripts explicitly. Nothing is implicit.
# -----------------------------------------------------------------------------

def cmd-exists [name: string] -> bool {
not (which $name | is-empty)
}

let root = $env.FILE_PWD

# Modules (export def ...): load with use

use ($root | path join "modules" "stdlib.nu") *
use ($root | path join "modules" "lib.nu") *

# Scripts (set $env / define aliases / prompt): load with source

source ($root | path join "prompt.nu")
source ($root | path join "alias.nu")

# Local behavioral overrides (ignored by default)

let local_init = ($root | path join "local" "init.local.nu")
if ($local_init | path exists) {
source $local_init
}

# Convenience: ensure edit_mode stays 
# vi if local overrides do weird things.

$env.config = ($env.config | upsert edit_mode "vi")
$env.config = ($env.config | upsert buffer_editor ($env.EDITOR | default "nvim"))

# Optional: raise open file limit (Linux)

try { ulimit -Sn 65535 } catch { null }

EOF

# -----------------------------------------------------------------------------
# repo/prompt.nu (no let-env; no legacy flags; starship optional)
# -----------------------------------------------------------------------------
write_file "$repo_dir/prompt.nu" 0644 <<'EOF'
# -----------------------------------------------------------------------------
# prompt.nu (Nu 0.109+)
# Prefer Starship if installed; otherwise a small built-in prompt.
# -----------------------------------------------------------------------------
def cmd-exists [name: string] -> bool {
not (which $name | is-empty)
}

def prompt-cwd [] -> string {
$env.PWD | str replace $env.HOME "~"
}

def prompt-git-branch [] -> string {
try {
^git rev-parse --abbrev-ref HEAD | str trim
} catch {
""
}
}

def prompt-left [] -> string {
let cwd = (prompt-cwd)
let br = (prompt-git-branch)
if ($br | is-empty) {
$"($cwd)"
} else {
$"($cwd) ($br)"
}
}

if (cmd-exists starship) {

Starship prompt; relies on your starship.toml (if any).

$env.PROMPT_COMMAND = {||
starship prompt --cmd-duration $env.CMD_DURATION_MS --status=$env.LAST_EXIT_CODE
}
$env.PROMPT_COMMAND_RIGHT = {|| "" }
$env.PROMPT_INDICATOR = {|| "" }
} else {
$env.PROMPT_COMMAND = {|| $"(prompt-left)\n〉 " }
$env.PROMPT_COMMAND_RIGHT = {|| "" }
$env.PROMPT_INDICATOR = {|| "" }
}

EOF

# -----------------------------------------------------------------------------
# repo/alias.nu (keep conservative; do not override builtins by default)
# -----------------------------------------------------------------------------
write_file "$repo_dir/alias.nu" 0644 <<'EOF'
# -----------------------------------------------------------------------------
# alias.nu
# Conservative aliases. Avoid overriding Nu builtins by default.
# -----------------------------------------------------------------------------
alias q = exit
alias c = clear

# Shortcuts

alias e = edit
alias v = nvim

# Git shortcuts (external)

alias gs = ^git status
alias gl = ^git log --oneline --decorate -n 20

EOF

# -----------------------------------------------------------------------------
# modules/stdlib.nu (small helpers)
# -----------------------------------------------------------------------------
write_file "$repo_dir/modules/stdlib.nu" 0644 <<'EOF'
# -----------------------------------------------------------------------------
# modules/stdlib.nu
# Small helpers used by other modules/scripts.
# -----------------------------------------------------------------------------
export def and-then [block: block] {
if not ($in | is-empty) { do $block }
}

export def or-else [block: block] {
if not ($in | is-empty) { $in } else { do $block }
}

export def unwrap-only [] {
let head = ($in | and-then { take 2 })
let n = ($head | length)
if $n == 1 {
$head | first
} else if $n == 0 {
error make { msg: "unwrap-only: input is empty" }
} else {
error make { msg: "unwrap-only: input has length > 1" }
}
}

EOF

# -----------------------------------------------------------------------------
# modules/lib.nu (Linux-friendly utilities; guarded by cmd-exists)
# -----------------------------------------------------------------------------
write_file "$repo_dir/modules/lib.nu" 0644 <<'EOF'
# -----------------------------------------------------------------------------
# modules/lib.nu
# Linux-friendly utilities. Keep dependencies optional and guarded.
# -----------------------------------------------------------------------------
def cmd-exists [name: string] -> bool {
not (which $name | is-empty)
}

# Edit a file/dir using $env.EDITOR (defaults configured in env.nu).

export def edit [path?: string] {
let p = ($path | default ".")
^($env.EDITOR | default "nvim") ($p | path expand)
}

# Open a file/dir in VS Code (if installed).

export def vscode [path?: string] {
if not (cmd-exists code) {
error make { msg: "VS Code CLI 'code' not found in PATH." }
}
let p = ($path | default ".")
^code ($p | path expand)
}

# Open a file/dir in Sublime (if installed).

export def sublime [path?: string] {
if not (cmd-exists subl) {
error make { msg: "Sublime CLI 'subl' not found in PATH." }
}
let p = ($path | default ".")
^subl -n ($p | path expand)
}

# Browse directories/files using fzf; open files in VS Code by default.

export def browse [dir: string = "."] {
if not (cmd-exists fzf) {
error make { msg: "fzf not found in PATH." }
}
let d = ($dir | path expand)
let choice = (
ls $d
| get name
| sort -i
| to text
| ^fzf --tac --cycle --prompt="browse> "
| str trim
)
if ($choice | is-empty) { return }

if (($choice | path type) == "dir") {
browse $choice
} else {
# Default opener: VS Code if present, else $EDITOR.
if (cmd-exists code) {
^code ($choice | path expand)
} else {
edit $choice
}
}
}

EOF

# -----------------------------------------------------------------------------
# Optional: install wrappers now
# -----------------------------------------------------------------------------

if [[ "$do_install" == "1" ]]; then
nu_dir="${XDG_CONFIG_HOME:-$HOME/.config}/nushell"
mkdir -p "$nu_dir"

backup_if_exists "$nu_dir/env.nu"
backup_if_exists "$nu_dir/config.nu"

cat >"$nu_dir/env.nu" <<EOF
# Wrapper generated by nushell-config-bootstrap.sh
source-env $repo_dir/env.nu
EOF

cat >"$nu_dir/config.nu" <<EOF
# Wrapper generated by nushell-config-bootstrap.sh
source $repo_dir/config.nu
EOF
fi

printf 'Wrote repo files to: %s\n' "$repo_dir"
printf 'Next:\n'
printf ' 1) (Optional) Install wrappers: %s\n' "$repo_dir/scripts/install.sh"
printf ' 2) Start nu: nu\n'
printf ' 3) Customize local overrides:\n'
printf ' %s\n' "$repo_dir/local/env.local.nu"
printf ' %s\n' "$repo_dir/local/init.local.nu"

::contentReference[oaicite:0]{index=0}
